import{S as u,a as p,i as n}from"./assets/vendor-5401a4b0.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const m=document.querySelector(".gallery");let d=new u(".gallery a",{captionsData:"alt",captionDelay:250});function y(a){const{webformatURL:t,largeImageURL:r,tags:i,likes:e,views:s,comments:l,downloads:c}=a;return`<li class="item"> <a class="gallery-item" href="${r}">
                 <img class="gallery-image"
                    src="${t}"
                    alt="${i}"/>
            </a>
            <ul class="descr">
            <li class="descr-item"><p class="descr-title">Likes<span class="descr-value">${e}</span></p></li>
            <li class="descr-item"><p class="descr-title">Views<span class="descr-value"> ${s}</span></p></li>
            <li class="descr-item"><p class="descr-title">Comments<span class="descr-value"> ${l}</span></p></li>
            <li class="descr-item"><p class="descr-title">Downloads<span class="descr-value"> ${c}</span></p></li>
            </ul>
            </li>`}function f(a){const t=a.hits.map(r=>y(r)).join("");m.innerHTML=t,d.refresh()}async function g(a){const t={key:"42343629-db0a88f68e5938b107ae69266",q:`${a.trim()}`.split(" ").map(e=>e.toLowerCase().trim()).join("+"),image_type:"photo",orientation:"horizontal",safesearch:!0},r=`https://pixabay.com/api/?key=${t.key}&q=${t.q}&image-type=${t.image_type}&orientation=${t.orientation}&safesearch=${t.safesearch}`;return(await p.get(r)).data}const h=document.querySelector(".form"),$=document.querySelector(".gallery"),o=document.querySelector(".loader");o.style.display="none";h.addEventListener("submit",a=>{a.preventDefault(),$.innerHTML="";const t=a.target.elements.input.value.trim();if(t===""){n.warning({message:"Please enter a valid request!",position:"topRight"});return}o.style.display="block",g(t).then(r=>{r.hits.length===0?n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):f(r)}).catch(r=>{console.log(r)}).finally(()=>{o.style.display="none"}),a.target.reset()});
//# sourceMappingURL=commonHelpers.js.map
