import{a as p,S as L,i as b}from"./assets/vendor-5401a4b0.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function l(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(t){if(t.ep)return;t.ep=!0;const r=l(t);fetch(t.href,r)}})();p.defaults.baseURL="https://pixabay.com/api/";async function y(e,s=1){return(await p.get("",{params:{key:"42343629-db0a88f68e5938b107ae69266",q:`${e.trim()}`.split(" ").map(o=>o.toLowerCase().trim()).join("+"),image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:15}})).data}const v=document.querySelector(".gallery");let w=new L(".gallery a",{captionsData:"alt",captionDelay:250});function S(e){const{webformatURL:s,largeImageURL:l,tags:o,likes:t,views:r,comments:n,downloads:h}=e;return`<li class="item"> <a class="gallery-item" href="${l}">
                 <img class="gallery-image"
                    src="${s}"
                    alt="${o}"/>
            </a>
            <ul class="descr">
            <li class="descr-item"><p class="descr-title">Likes<span class="descr-value">${t}</span></p></li>
            <li class="descr-item"><p class="descr-title">Views<span class="descr-value"> ${r}</span></p></li>
            <li class="descr-item"><p class="descr-title">Comments<span class="descr-value"> ${n}</span></p></li>
            <li class="descr-item"><p class="descr-title">Downloads<span class="descr-value"> ${h}</span></p></li>
            </ul>
            </li>`}function q(e){const s=e.hits.map(l=>S(l)).join("");v.insertAdjacentHTML("beforeend",s),w.refresh()}const $=document.querySelector(".form"),f=document.querySelector(".gallery"),c=document.querySelector(".loader"),a=document.querySelector(".load-more-btn");let u,i,m;c.style.display="none";a.classList.add("hidden");$.addEventListener("submit",P);a.addEventListener("click",M);async function P(e){if(e.preventDefault(),f.innerHTML="",u=e.target.elements.input.value.trim(),u===""){d("Please enter a valid request!");return}c.style.display="block",i=1;try{const s=await y(u,i);m=Math.ceil(s.totalHits/15),a.classList.remove("hidden"),i>=m?a.classList.add("hidden"):a.classList.remove("hidden"),g(s)}catch(s){console.error(s),d("Unable to get images")}finally{c.style.display="none"}}async function M(){c.style.display="block",i++;try{const e=await y(u,i);g(e),O()}catch(e){console.error(e),d("Unable to get images")}finally{c.style.display="none"}}function g(e){if(e.hits.length===0){d("Sorry, there are no images matching your search query. Please try again!");return}else q(e);i>=m?(a.classList.add("hidden"),d("We are sorry, but you have reached the end of search results.")):a.classList.remove("hidden")}function d(e){b.error({message:e,position:"topRight"})}function O(){const e=f.firstElementChild.getBoundingClientRect().height;scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
